### Running Bayesian SR model 
Bayesian SR Analysis model is coded in **JAGS** (see Model Codes Tab). 
The model estimates following parameters


|Parameter |       | Prior  |      |    Note  |
|  ------- |-----:| -------:|-----:|-------:|
|_________|__|__________________|__|________________________|
| $ln(\alpha)$  | | $ln(\alpha) \sim U(0,10)$ | | All models   | 
| $\beta$    |  |   $\beta \sim U(0,10)$  | | All models   | 
| $\sigma$    |   |   $\sigma \sim U(0,10)$  | | All models    | 
| $\phi$    |   | $\phi \sim U(-1,1)$   |  |**AR1 model**  | 
| $\varepsilon_{0}$ |   |  $\varepsilon_{0} \sim N(0,100)$   |  |**AR1 model**  | 
| $\sigma _{\omega}$|   |  $\sigma _{\omega} \sim U(0,10)$   |  |**Time varying alpha model**| 


$$ln(`R) \sim N(\mu,{\sigma}^{2})$$
where $\mu$ is Ricker or Beverton-Holt Spawner recurit equations.

In JAGS model, 
Log linearlized form of Ricker and Beverton-Holt model was fitted.  

$$ln(`R)= ln(\alpha )-\beta s+ln(S)+\varepsilon$$

Beverton-Holt SR model is
$$ln('R)=ln(\alpha )-ln(1+\beta s)+ln(S)+e$$
where
$$ s = S\cdot{10}^{-d}   $$
and  
$$ d = Int(log(S)) $$
This modeling formulation ensures that $ln(\alpha)$ and $\beta$ about the same number rage, which makes it easier to estimate model parameters. 

#### AR(1) model option 
AR(1) model (First-order autoregresssion model) assumes that error is serially correlated or that the value of residual at time *t* is a linear function of the residual at tune *t-1*. 
This is modeled as 
$${\varepsilon_{t}}=\phi {\varepsilon_{t-1}}+{\nu_{t}}$$ 
where ${\nu_{t}} \sim N(0,{\sigma _{\nu }}^{2})$

### Time variant alpha model option  
Time variant alpha model assumes that alpha takes random walk process. 
$${ln(\alpha )_{t}}={ln(\alpha )_{t-1}}+{\omega_{t}}$$ 
where ${\omega_{t}} \sim N(0,{\sigma _{\omega }}^{2})$


#### Biological reference points
Following biological reference points are generated from the model 
* Seq   Spawner abundance expected to produce the same number of recruits
* Smsy  Spawner abundance espected to produce the maximum number of yield (MSY) * Umsy  Exploitation rate exepected to produce MSY
* Smax  Spawner abundance expected to produce the maximum number of recruits

##### Seq
SEQ is also the point where spawner-recruit curve intercepts 1:1 (replacement) line. 

**Ricker model** 
$$Seq =  \frac{ln(\alpha)}{\beta}$$
Smsy and Umsy of Riker model is an approximate where 0 < $ln(\alpha)$ < 3(Hilbon 1985) 

$$Smsy =  Seq(0.5-0.07ln(\alpha))$$

$$Umsy =  ln(\alpha)(0.5-0.07ln(\alpha))$$
$$Smax =  \frac{1}{\beta}$$
**Beverton-Holt model** 
$$Seq =  \frac{\alpha -1}{\beta}$$
$$Smsy =  \frac{\sqrt{\alpha} -1}{\beta}$$
$$Umsy = 1- \sqrt{\frac{1}{\alpha}}$$
Smax does bit exist in Beverton-Holt model
$$Smax = NA$$







